/**
 * Tool Registry & Dynamic Tool Auto-Update Engine
 * Enables autonomous codebase evolution by registering native tools and dynamically
 * appending new tools generated by the runtime agent into permanent storage.
 */

export interface ToolParameter {
  type: string;
  description: string;
  required?: boolean;
}

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, ToolParameter>;
  category: 'ml' | 'revenue' | 'self_healing' | 'integration' | 'custom';
  createdAt: string;
  updatedAt?: string;
  version: string;
  isNative: boolean;
  handlerName?: string;
}

<<<<<<< HEAD
export const TOOL_REGISTRY: ToolDefinition[] = [
=======
const TOOL_REGISTRY: ToolDefinition[] = [
>>>>>>> 8fab0ab (Deploy to AWS EC2 and AWS Amplify)
  {
    name: 'calculate_optimal_bid',
    description: 'Calculates dynamic optimal bid using percentile strategy and profitability floor based on client budget and category.',
    parameters: {
      budgetMax: { type: 'number', description: 'Maximum client budget if provided', required: false },
      budgetMin: { type: 'number', description: 'Minimum client budget if provided', required: false },
      category: { type: 'string', description: 'Domain category (e.g., AI Consulting, React, etc.)', required: false },
    },
    category: 'revenue',
    createdAt: '2026-09-08T00:00:00.000Z',
    version: '1.0.0',
    isNative: true,
  },
  {
    name: 'score_client_trust',
    description: 'Computes ml_client_score (0-100) based on client hire history, ratings, and payment verification to eliminate scam projects.',
    parameters: {
      hireRate: { type: 'number', description: 'Client historical hire rate percentage', required: true },
      rating: { type: 'number', description: 'Client star rating (0-5)', required: true },
      paymentVerified: { type: 'boolean', description: 'Whether client payment method is verified', required: true },
      hiresCount: { type: 'number', description: 'Total previous hires by client', required: false },
    },
    category: 'ml',
    createdAt: '2026-09-08T00:00:00.000Z',
    version: '1.0.0',
    isNative: true,
  },
  {
<<<<<<< HEAD
    name: 'execute_autonomous_payout',
    description: 'Autonomous Cash-Out Engine: triggers immediate PayPal milestone release or routes to human-in-the-loop based on risk bands.',
    parameters: {
      workOrderId: { type: 'string', description: 'Work Order identifier', required: true },
      amount: { type: 'number', description: 'Gross payout amount in USD', required: true },
      workerEmail: { type: 'string', description: 'Beneficiary worker PayPal email', required: true },
=======
    name: 'record_receivable',
    description: 'Receivables Engine: logs fulfilled work order milestones and accrues outstanding client receivables.',
    parameters: {
      workOrderId: { type: 'string', description: 'Work Order identifier', required: true },
      amount: { type: 'number', description: 'Gross receivable amount in USD', required: true },
      clientName: { type: 'string', description: 'Client name or account', required: false },
>>>>>>> 8fab0ab (Deploy to AWS EC2 and AWS Amplify)
    },
    category: 'revenue',
    createdAt: '2026-09-08T00:00:00.000Z',
    version: '1.0.0',
    isNative: true,
  },
  {
    name: 'evaluate_bankruptcy_guardrails',
    description: 'Enforces stop-loss controls ($500 spend without revenue) and profit thresholds (revenue/bids < 1.0 reduces MAX_BID_AMOUNT).',
    parameters: {
      windowDays: { type: 'number', description: 'Rolling time window in days', required: false },
    },
    category: 'revenue',
    createdAt: '2026-09-08T00:00:00.000Z',
    version: '1.0.0',
    isNative: true,
  },
  {
    name: 'watchdog_health_remediation',
    description: 'Monitors /api/health and recovers process and connection pools via automated self-healing.',
    parameters: {
      action: { type: 'string', description: 'Recovery action (restart_pm2, flush_redis, reset_pool)', required: false },
    },
    category: 'self_healing',
    createdAt: '2026-09-08T00:00:00.000Z',
    version: '1.0.0',
    isNative: true,
  },
];

/**
 * Append a newly synthesized tool definition to the permanent registry
 */
export function appendDynamicTool(toolDef: Omit<ToolDefinition, 'createdAt' | 'version' | 'isNative'> & { version?: string }): {
  success: boolean;
  tool: ToolDefinition;
  message: string;
} {
  const existingIdx = TOOL_REGISTRY.findIndex((t) => t.name === toolDef.name);
  const now = new Date().toISOString();

  if (existingIdx >= 0) {
    TOOL_REGISTRY[existingIdx] = {
      ...TOOL_REGISTRY[existingIdx],
      ...toolDef,
      updatedAt: now,
      isNative: false,
      version: toolDef.version || '1.1.0',
    };
    return {
      success: true,
      tool: TOOL_REGISTRY[existingIdx],
      message: `Updated existing dynamic tool "${toolDef.name}" in TOOL_REGISTRY.`,
    };
  }

  const newTool: ToolDefinition = {
    ...toolDef,
    createdAt: now,
    version: toolDef.version || '1.0.0',
    isNative: false,
  };

  TOOL_REGISTRY.push(newTool);
  console.log(`✨ [ToolRegistry] Dynamically registered new native tool: "${newTool.name}"`);

  return {
    success: true,
    tool: newTool,
    message: `Appended tool "${newTool.name}" to TOOL_REGISTRY.`,
  };
}

/**
 * Retrieve all registered native & dynamic tools
 */
export function getAllRegisteredTools(): ToolDefinition[] {
  return [...TOOL_REGISTRY];
}
